test = {   'name': 'q2_3_2',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> # It looks like you are not making an array.;\n>>> import numpy as np;\n>>> assert type(total_charges) == np.ndarray\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> import numpy as np;\n>>> assert sum(abs(total_charges - np.array([24.144, 47.88, 37.212]))) < 1e-6\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
