test = {   'name': 'q1_2',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': ">>> import numpy as np;\n>>> # It looks like you didn't make an array;\n>>> assert type(book_title_words) == np.ndarray\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> # It looks like you included commans in the text.;\n>>> assert not any([',' in text for text in book_title_words])\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> # It looks like you didn't include both words in the last pice of text.;\n>>> assert 'and' in book_title_words.item(2) \n",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert len(book_title_words) == 3\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert book_title_words.item(0) == "Eats"\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert book_title_words.item(1) == "Shoots"\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert book_title_words.item(2) == "and Leaves"\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
