test = {   'name': 'q3_5',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> # It looks like you multiplited the differences by 5*9 instead of 5/9;\n>>> assert celsius_temperature_ranges.item(0) != 540\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert round(sum(celsius_temperature_ranges)) == 768487.0\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert len(celsius_temperature_ranges) == 65000\n', 'hidden': False, 'locked': False},
                                   {'code': '>>> assert celsius_temperature_ranges.item(1) == 10.0\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
