test = {   'name': 'q3_3_1',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> assert time == 1.2\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # The question asks for the units in meters but the text used centimeters;\n>>> assert estimated_distance_m != 113\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
