test = {   'name': 'q3_5',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> # It looks like you forgot to assign a value to farmers_markets_without_fmid;\n>>> assert farmers_markets_without_fmid != ...\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert farmers_markets_without_fmid.num_columns == 57\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
