test = {   'name': 'q3_7',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> # It looks like you forgot to set the variable nyc_markets;\n>>> assert nyc_markets.num_rows != ...\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # HINT: It looks like your predicate was;\n>>> #   "are.equal_to("New York")";\n>>> assert nyc_markets.num_rows != 45\n',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert nyc_markets.num_rows == 12\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
