test = {   'name': 'q4_2_1',
    'points': 2,
    'suites': [   {   'cases': [   {'code': '>>> assert simulate_resample(observations).num_rows == 17\n', 'hidden': False, 'locked': False},
                                   {   'code': '>>> # Your resample should only have the column "serial number";\n>>> assert simulate_resample(observations).labels[0] == observations.labels[0]\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
