test = {   'name': 'q2_3',
    'points': 3,
    'suites': [   {   'cases': [   {   'code': '>>> # Double check that your salary_range function is correct;\n>>> assert salary_range(make_array(5, 1, 20, 1000)) == 999\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert set(department_ranges.labels) == set(['assistant professor', 'associate professor', 'department', 'lecturer', 'professor'])\n",
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> assert sum(department_ranges.column(1)) == 2976273.0\n', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
