test = {   'name': 'q2_1_5',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': ">>> assert [most_common('Genre', close_movies.take(range(k))) for k in np.arange(1, 5)] == ['thriller', 'thriller', 'thriller', 'thriller']\n",
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': ">>> assert [most_common('Genre', close_movies.take(range(4, k, -1))) for k in np.arange(3, -1, -1)] == ['comedy', 'comedy', 'comedy', 'thriller']\n",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
